# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myesp_tool/ui/settingsdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName("SettingsDialog")
        SettingsDialog.resize(420, 380)
        self.verticalLayout = QtWidgets.QVBoxLayout(SettingsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_serial = QtWidgets.QGroupBox(SettingsDialog)
        self.groupBox_serial.setObjectName("groupBox_serial")
        self.formLayout_serial = QtWidgets.QFormLayout(self.groupBox_serial)
        self.formLayout_serial.setObjectName("formLayout_serial")
        self.label_port = QtWidgets.QLabel(self.groupBox_serial)
        self.label_port.setObjectName("label_port")
        self.formLayout_serial.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_port)
        self.layout_port = QtWidgets.QHBoxLayout()
        self.layout_port.setObjectName("layout_port")
        self.edit_port = QtWidgets.QComboBox(self.groupBox_serial)
        self.edit_port.setEditable(True)
        self.edit_port.setObjectName("edit_port")
        self.layout_port.addWidget(self.edit_port)
        self.btn_refresh_ports = QtWidgets.QPushButton(self.groupBox_serial)
        self.btn_refresh_ports.setObjectName("btn_refresh_ports")
        self.layout_port.addWidget(self.btn_refresh_ports)
        self.formLayout_serial.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.layout_port)
        self.label_baudrate = QtWidgets.QLabel(self.groupBox_serial)
        self.label_baudrate.setObjectName("label_baudrate")
        self.formLayout_serial.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_baudrate)
        self.edit_baudrate = QtWidgets.QComboBox(self.groupBox_serial)
        self.edit_baudrate.setEditable(True)
        self.edit_baudrate.setObjectName("edit_baudrate")
        self.formLayout_serial.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.edit_baudrate)
        self.label_bytesize = QtWidgets.QLabel(self.groupBox_serial)
        self.label_bytesize.setObjectName("label_bytesize")
        self.formLayout_serial.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_bytesize)
        self.edit_bytesize = QtWidgets.QComboBox(self.groupBox_serial)
        self.edit_bytesize.setObjectName("edit_bytesize")
        self.formLayout_serial.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.edit_bytesize)
        self.label_stopbits = QtWidgets.QLabel(self.groupBox_serial)
        self.label_stopbits.setObjectName("label_stopbits")
        self.formLayout_serial.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_stopbits)
        self.edit_stopbits = QtWidgets.QComboBox(self.groupBox_serial)
        self.edit_stopbits.setObjectName("edit_stopbits")
        self.formLayout_serial.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.edit_stopbits)
        self.label_parity = QtWidgets.QLabel(self.groupBox_serial)
        self.label_parity.setObjectName("label_parity")
        self.formLayout_serial.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_parity)
        self.edit_parity = QtWidgets.QComboBox(self.groupBox_serial)
        self.edit_parity.setObjectName("edit_parity")
        self.formLayout_serial.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.edit_parity)
        self.label_timeout = QtWidgets.QLabel(self.groupBox_serial)
        self.label_timeout.setObjectName("label_timeout")
        self.formLayout_serial.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_timeout)
        self.edit_timeout = QtWidgets.QDoubleSpinBox(self.groupBox_serial)
        self.edit_timeout.setDecimals(1)
        self.edit_timeout.setMinimum(0.0)
        self.edit_timeout.setMaximum(60.0)
        self.edit_timeout.setSingleStep(0.5)
        self.edit_timeout.setProperty("value", 10.0)
        self.edit_timeout.setObjectName("edit_timeout")
        self.formLayout_serial.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.edit_timeout)
        self.verticalLayout.addWidget(self.groupBox_serial)
        self.groupBox_general = QtWidgets.QGroupBox(SettingsDialog)
        self.groupBox_general.setObjectName("groupBox_general")
        self.formLayout_general = QtWidgets.QFormLayout(self.groupBox_general)
        self.formLayout_general.setObjectName("formLayout_general")
        self.verticalLayout.addWidget(self.groupBox_general)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(SettingsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(SettingsDialog)
        self.buttonBox.rejected.connect(SettingsDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingsDialog.setWindowTitle(_translate("SettingsDialog", "设置"))
        self.groupBox_serial.setTitle(_translate("SettingsDialog", "串口设置"))
        self.label_port.setText(_translate("SettingsDialog", "端口"))
        self.btn_refresh_ports.setText(_translate("SettingsDialog", "刷新"))
        self.label_baudrate.setText(_translate("SettingsDialog", "波特率"))
        self.label_bytesize.setText(_translate("SettingsDialog", "数据位"))
        self.label_stopbits.setText(_translate("SettingsDialog", "停止位"))
        self.label_parity.setText(_translate("SettingsDialog", "校验"))
        self.label_timeout.setText(_translate("SettingsDialog", "超时 (秒)"))
        self.edit_timeout.setSuffix(_translate("SettingsDialog", " s"))
        self.groupBox_general.setTitle(_translate("SettingsDialog", "其他设置"))
