name: Release

on:
  - push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync

      - name: Build with PyInstaller
        run: uv run pyinstaller -F -w --name MyESPTool myesp_tool/main.py

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/MyESPTool.exe
